---

version: "3"

services:
  petclinic:
    image: tomcat-petclinic
    build: 
      context: ./tomcat_petclinic
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - "db"
    command: ["./wait-for-it.sh", "db:3306", "--timeout=300" ,"--", "catalina.sh", "run"]

  db:
    image: mysql:5.7
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      #ports:
      #- 3306:3306

